export const mockProducts = [
  {
    id: "prod_1",
    title: "AeroSound X500 Noise-Canceling Headphones",
    type: "physical",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    ratingCount: 142,
    inStock: true,
    deliveryInfo: "Ships in 1-2 business days",
    category: "Audio Equipment",
  },
  {
    id: "prod_2",
    title: "Minimalist Full-Grain Leather Backpack",
    type: "physical",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
    price: 135.00,
    rating: 4.5,
    ratingCount: 88,
    inStock: true,
    deliveryInfo: "Free shipping worldwide",
    category: "Travel Gear",
  },
  {
    id: "prod_3",
    title: "React Enterprise Dashboard UI Kit - Pro License",
    type: "digital",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80",
    price: 89.00,
    originalPrice: 129.00,
    rating: 4.9,
    ratingCount: 64,
    inStock: true,
    deliveryInfo: "Instant Download & Lifetime Updates",
    category: "Software & Coding",
  },
  {
    id: "prod_4",
    title: "Premium 3D Abstract Glass Icon Pack",
    type: "digital",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    price: 24.50,
    rating: 4.2,
    ratingCount: 18,
    inStock: true,
    deliveryInfo: "Immediate Access (Figma & PNG)",
    category: "Design Resources",
  },
  {
    id: "prod_5",
    title: "KeyPro Custom Mechanical Keyboard (Linear Red Switches)",
    type: "physical",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&auto=format&fit=crop&q=80",
    price: 160.00,
    originalPrice: 180.00,
    rating: 4.7,
    ratingCount: 29,
    inStock: false,
    deliveryInfo: "Restocking soon",
    category: "Computer Peripherals",
  },
];
